apiVersion: autoscaling/v2              # Versão da API do HPA
kind: HorizontalPodAutoscaler                  # Tipo de objeto
metadata:
  name: lanchonetedobairro-hpa                                  # Nome do HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1                         # Versão da API do objeto que está sendo escalado
    kind: Deployment                             # Tipo do objeto que está sendo escalado (neste caso, um Deployment)
    name: lanchonetedobairro-api                               # Nome do Deployment a ser escalado
  minReplicas: 1                                # Número mínimo de réplicas
  maxReplicas: 10                               # Número máximo de réplicas
  metrics:                                      # Lista de métricas a serem monitoradas
  - type: Resource                               # Tipo de métrica (neste caso, um recurso como CPU ou memória)
    resource:
      name: cpu                                 # Nome do recurso a ser monitorado
      target:
        type: Utilization                       # Tipo de métrica (utilização percentual)
        averageUtilization: 80                  # Meta de utilização média de CPU (neste caso, 50%)
